name: Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mdviewer-app
  LOCAL_TAG: markdown-viewer-app:latest
  REMOTE_TAG: gcr.io/${PROJECT_ID}/${LOCAL_TAG}

jobs:
  setup-build-publish-deploy:
    name: Setup,Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '347.0.0'
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GH_SA_GCP_CREDENTIALS }}
          export_default_credentials: true
          project_id: mdviewer-app

      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - name: Configuration
        run: |
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: docker build -t markdown-viewer-app:latest .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker tag markdown-viewer-app:latest gcr.io/mdviewer-app/markdown-viewer-app:latest
          docker push gcr.io/mdviewer-app/markdown-viewer-app
      # Deploy updated image
      - name: Deploy
        run: |
          gcloud run deploy 'mdviewer-app' --image=gcr.io/mdviewer-app/markdown-viewer-app:latest --platform=managed --region=europe-west1
