name: Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mdviewer-app
  LOCAL_TAG: markdown-viewer-app:latest
  REMOTE_TAG: gcr.io/${PROJECT_ID}/${LOCAL_TAG}

jobs:
  setup-build-publish-deploy:
    name: Setup,Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '347.0.0'
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GH_SA_GCP_CREDENTIALS }}
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - name: Configuration
        run: |
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build & Publish
        run: |
          gcloud config set project mdviewer-app
          gcloud builds submit --tag gcr.io/mdviewer-app/markdown-viewer-app:latest

      # Push the Docker image to Google Container Registry
      - name: Deploy
        run: |
          gcloud run deploy markdown-viewer-app:latest --image gcr.io/mdviewer-app/markdown-viewer-app:latest \
          --platform managed \
          --allow-unauthenticated \
          --memory 512M
